### PR TITLE
Always return a Promise from async triggers, fixes #216

### LINKED ISSUE #216: Asynchronous actions not returning promises?
From the current documentation on "Asynchronous actions as Promises" I get the impression that the asynchronous actions would return a promise which is resolved when the `completed` child action is called.

https://github.com/spoike/refluxjs/blob/0b3f14f92a6ae5a969b0a5a738de2434cdae15e9/README.md#asynchronous-actions-as-promises

But that's not the case?

ie. I assumed following would work

```js
var Reflux = require("reflux");                         
                                                        
var action = Reflux.createAction({ asyncResult: true });
                                                                                                      
action.listen(function() {                              
                                                        
    setTimeout(this.completed, 1000);                                           
                                                        
});                                                     
                                                                                                 
action().then(function() {                              
    console.log("Done!");                               
});                                                     

```

but it fails with `TypeError: Cannot call method 'then' of undefined`

### PR DESCRIPTION
**Pull request by snorp**

### CODE REVIEW

File: src/createAction.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ var createAction = function(definition) {
     }, Reflux.PublisherMethods, Reflux.ActionMethods, definition);
 
     var functor = function() {
-        functor[functor.sync?"trigger":"triggerAsync"].apply(functor, arguments);
+        return functor[functor.sync?"trigger":"triggerPromise"].apply(functor, arguments);
```
Comment (robcolburn) [inline src/createAction.js]: This is the primary way `triggerAsync` is fired, you may want to deprecate `triggerAsync` or have it always call `triggerPromise`.  If you do that, you'll need to move `triggerAsync`'s logic into `triggerPromise`.
